package com.portfoliotracker.dao;

import com.portfoliotracker.mapper.UserAccountMapper;
import com.portfoliotracker.model.UserAccount;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Repository;
import java.sql.PreparedStatement;
import java.sql.Statement;

@Repository
public class UserAccountDaoImpl implements UserAccountDao {

    private final JdbcTemplate jdbcTemplate;

    public UserAccountDaoImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public UserAccount createUser(UserAccount user) {

        // userId is AUTO_INCREMENT and createdAt is set by the database, so both are left out of the INSERT.
        final String sql = """
                           INSERT INTO user_account (username, email, passwordHash)
                           VALUES (?, ?, ?)
                           """;

        // This is used to hold the ID generated by the database
        GeneratedKeyHolder keyHolder = new GeneratedKeyHolder();

        jdbcTemplate.update(connection -> {
            PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            statement.setString(1, user.getUsername());
            statement.setString(2, user.getEmail());
            statement.setString(3, user.getPasswordHash());
            return statement;
        }, keyHolder);

        return findById(keyHolder.getKey().intValue());
    }

    @Override
    public UserAccount findByUsername(String username) {

        final String sql = """
                           SELECT *
                           FROM user_account
                           WHERE username = ?
                           """;

        // queryForObject throws when no row matches, so that case is turned into null.
        try {
            return jdbcTemplate.queryForObject(sql, new UserAccountMapper(), username);
        } catch (EmptyResultDataAccessException e) {
            return null;
        }
    }

    @Override
    public UserAccount findByEmail(String email) {

        final String sql = """
                           SELECT *
                           FROM user_account
                           WHERE email = ?
                           """;

        try {
            return jdbcTemplate.queryForObject(sql, new UserAccountMapper(), email);
        } catch (EmptyResultDataAccessException e) {
            return null;
        }
    }

    @Override
    public UserAccount findById(int userId) {

        final String sql = """
                           SELECT *
                           FROM user_account
                           WHERE userId = ?
                           """;

        try {
            return jdbcTemplate.queryForObject(sql, new UserAccountMapper(), userId);
        } catch (EmptyResultDataAccessException e) {
            return null;
        }
    }
}
